export const stats = [
  "88% of developers prefer dark mode over light mode.",
  "69% of developers use Visual Studio Code as their primary code editor.",
  "42% of developers visit Stack Overflow every single day.",
  "75% of developers say they can’t code without coffee ☕.",
  "58% of developers work better while listening to music.",
  "64% of developers have more than 3 tabs open at all times.",
  "79% of developers say naming things is the hardest part of coding.",
  "38% of developers have debugged code by talking to a rubber duck 🦆.",
  "60% of developers learned programming through online tutorials and YouTube.",
  "27% of developers have pushed broken code to production (and lived to tell the tale).",
  "45% of developers prefer working at night - true code vampires 🧛‍♂️.",
  "31% of devs use TODO comments as future life plans.",
  "82% of developers have used Google to search for the same error more than 3 times in one day.",
  "33% of developers still fear merge conflicts more than horror movies.",
  "50% of junior developers think Git is sorcery 🧙‍♂️.",
  "91% of developers secretly judge other people's indentation style.",
  "56% of developers say their best ideas come in the shower 🚿.",
  "43% of developers have built a side project they never launched.",
  "28% of developers talk to their code (and it sometimes listens).",
  "70% of developers prefer keyboard shortcuts over clicking UI buttons.",
  "49% of devs write code that only future-me will understand.",
  "39% of developers have cried because of CSS 😢.",
  "84% of developers have written code at 2 AM and regretted it at 9 AM.",
  "26% of developers have named a variable 'thing', 'stuff', or 'data'.",
  "62% of developers would rather refactor than write new tests.",
  "57% of devs think React is both amazing and a headache.",
  "40% of developers follow a tutorial without finishing the project.",
  "46% of developers have Googled 'how to center a div' at least once.",
  "68% of developers say JavaScript is their love-hate relationship.",
  "23% of developers accidentally deployed to production on a Friday.",
  "55% of developers find documentation more confusing than code.",
  "74% of devs have at least one abandoned GitHub repo.",
  "36% of developers own at least one mechanical keyboard.",
  "61% of devs plan features before building... and still change everything later.",
  "77% of developers have customized their VS Code theme.",
  "25% of developers use emojis in commit messages 😂.",
  "66% of developers have tried coding in bed... once.",
  "52% of developers use AI tools like ChatGPT weekly.",
  "71% of developers think tabs vs spaces is still a valid debate.",
  "44% of devs code better after midnight snacks.",
  "58% of developers have more than 5 Chrome extensions installed.",
  "32% of developers hoard domains they'll never use.",
  "29% of devs have lost hours debugging a typo.",
  "59% of developers think StackOverflow should be a paid utility bill.",
  "35% of developers take their stand-up meetings sitting down.",
  "48% of devs have a backlog of over 10 unstarted side projects.",
  "40% of developers use a second monitor just for memes.",
  "73% of developers say finishing a feature is more satisfying than finishing a movie.",
  "53% of devs think 'technical debt' is a polite way to say 'oops'.",
  "62% of developers check GitHub more than their email.",
  "30% of developers have a plant named after a framework.",
  "69% of developers use YouTube as their primary learning tool.",
  "37% of devs start a new project just to avoid working on the old one.",
  "46% of developers think backend folks are wizards.",
  "65% of frontend devs silently cry when designs change after launch.",
  "28% of devs say their pet has interrupted a live coding session.",
  "59% of developers secretly enjoy fixing other people’s bugs.",
  "47% of developers have rewritten something that already existed... just better.",
  "75% of developers hate writing documentation - but read it religiously.",
  "34% of developers have written code that no longer makes sense even to them.",
  "29% of devs believe rubber duck debugging actually works.",
  "61% of developers have keyboard shortcuts they refuse to reveal.",
  "70% of devs have memorized their most common StackOverflow answers.",
  "43% of developers use AI just to double-check if their code is okay.",
  "56% of devs prefer terminal over GUI for serious work.",
  "40% of developers have a folder called 'final_final_real_final'.",
  "50% of developers talk to Siri about bugs (just in case).",
  "33% of devs tried to build their own note-taking app... and failed.",
  "48% of developers say switching tabs counts as cardio.",
  "36% of devs have more lines of console.log than actual code.",
  "60% of developers use dark mode to save their soul, not just battery.",
  "27% of devs have worked on a team where the project manager didn’t know what Git is.",
  "41% of developers copy code... and then understand it later.",
  "54% of developers believe a 10-minute bug takes 4 hours to fix.",
  "45% of devs have pushed code and hoped no one notices the bug.",
  "38% of developers drink tea, not coffee - but still pretend they’re wired.",
  "67% of devs enjoy learning new frameworks... until they see the docs.",
  "49% of developers use React even when they shouldn't.",
  "72% of devs forget semicolons... and let Prettier deal with it.",
  "33% of developers have deployed something that broke the UI on IE.",
  "59% of developers use Git every day but still fear rebase.",
  "35% of developers keep stickers on their laptops to hide the scratches.",
  "44% of devs believe bugs are just 'unexpected features'.",
  "51% of devs spend more time reading code than writing it.",
  "42% of developers think 'refactor' means 'let’s rewrite everything'.",
  "68% of developers have started a blog they never updated again.",
  "57% of devs watch coding tutorials while coding something else.",
  "36% of developers treat StackOverflow as their second brain.",
  "60% of devs find peace in deleting 500+ lines of legacy code.",
  "40% of devs keep GitHub stars like bookmarks.",
  "39% of developers have tried pair programming... and gone solo again.",
  "52% of developers name their variables after Pokémon or Star Wars.",
  "71% of devs say code is art... and bugs are just modern expressionism.",
  "29% of developers make memes instead of unit tests.",
  "43% of devs build landing pages before writing any backend.",
  "66% of developers use AI to explain their own code.",
  "38% of developers think TypeScript is both a blessing and a curse.",
  "55% of developers read changelogs like bedtime stories.",
  "26% of developers take lunch breaks with their debugger still running.",
  "48% of devs pretend they’re in The Matrix when typing fast.",
  "53% of developers say deleting code is more satisfying than writing it.",
  "69% of developers use the same password across all dev tools. 😬",
  "77% of developers think the first commit message should always be 'Initial commit'.",
];
