const trendingCSTopics = [
  "Web Development",
  "Data Structures and Algorithms",
  "Machine Learning",
  "Artificial Intelligence",
  "Python Programming",
  "C++ Programming",
  "System Design",
  "Operating Systems",
  "Computer Networks",
  "Database Management Systems",
  "Cloud Computing",
  "DevOps",
  "Cybersecurity",
  "Mobile App Development",
  "Blockchain Development",
  "Game Development",
  "Computer Architecture",
  "Linux and Shell Scripting",
  "Frontend Development (HTML, CSS, JS, React)",
  "Backend Development (Node.js, Django, Spring Boot)",
  "Software Engineering Principles",
  "Git and Version Control",
  "Data Science",
  "Natural Language Processing (NLP)",
  "Quantum Computing (Beginner Level)",
];
export default trendingCSTopics;